### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by sebelk** [genepattern/jupyter-wysiwyg#1]
I've installed and enabled using:

```
jupyter nbextension install --py jupyter_wysiwyg
jupyter nbextension enable jupyter_wysiwyg --py
```
And I can't see where is the wysiwyg....

I don't see any toolbar, menu, option to use wysiwyg mode.

Please could you see how to use it?

My platform:

- python-2.7.12-7.fc25.x86_64
- jupyter-notebook -V
- 4.2.2
- Fedora 25

Thanks in advance!

**Comment by sebelk** [comment]
Oh, shame on me! Yeah  I clicked on cell and appears a "Rich Text Editing"

**Comment by JocelynDelalande** [comment]
@sebelk any screenshot of that ? because I'm having the sameinitial  feeling as you… But I didn't find this "Rich text editing".

**Comment by tmtabor** [comment]
There's a screenshot of the button and tooltip here: https://www.dropbox.com/s/2hdxlpehghyoxj4/wysiwyg-button.jpg?dl=0

Just create a markdown cell and then select the cell. You'll see the buttons appear on the left side of the cell.

**Comment by JocelynDelalande** [comment]
@tmtabor 404 error on your dropbox link

**Comment by tmtabor** [comment]
You're right. I don't know why the Dropbox file isn't still there, but here it is hosted on a different site: http://imgur.com/a/m3zsx

The button you're looking for in on the far left side of the selected markdown cell.

**Comment by JocelynDelalande** [comment]
So… I do have the exact issue as @sebelk describe in his/her first comment. But for myself, it did not solve by itself.

**Comment by tmtabor** [comment]
No problem. Let's see if we can debug the issue. The first thing to do is to check for common errors. We need to determine if the extension is failing for you on the server-side or the client-side.

Try running `jupyter nbextension list` on the command line. Do you see a listing for *jupyter_wysiwyg/index*? Is it listed as *enabled* and validating as *OK*?

If you don't see it listed or it doesn't appear enabled, then we know the issue is with the installation of the extension. This is a common problem if, for example, you installed jupyter as root but didn't try enabling the nbextension as root. What happens is that jupyter will quietly fail to enable the nbextension, as the command doesn't have the right permissions to do so. This can be fixed by simply running the install and enable commands again, this time using sudo.

If you see the nbextension listed as installed, but it's not validating, then we know there is a server-side or configuration issue of some sort. Let me know if that's the case, and we can move on to debugging that.

On the other hand, if the extension is listed as both installed and enabled, you're likely experiencing some sort of client-side error. Let me know if that's the case, and we can move on in that direction.

**Comment by JocelynDelalande** [comment]
Ok, tryed again the whole process, using non-privilegged user (which I called `jupyter`). 

I don't know what I failed during my previous trials, but **it's working now**, thanks for your time :-)

**Comment by tmtabor** [comment]
No problem. Glad I could help.
